### ISSUE TITLE
Stop using the "triage" label

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/issue-triage#2]
As opposed to the "bundler" label, which I think is useful, unconditionally adding the "triage" label to every PR and issue seems useless to me, because it essentially means the same as no label.

Thoughts @bronzdoc?

**Comment by bronzdoc** [comment]
@deivid-rodriguez  I think nobody that contributes to Rubygems/Bundler likes it but me, and I will not die for them either. I'll remove it.

**Comment by bronzdoc** [comment]
@deivid-rodriguez done 
https://github.com/rubygems/issue-triage/commit/74ae3a3a606b4db898c33f8a1ee19cfda840b4e4

**Comment by deivid-rodriguez** [comment]
Thank you @bronzdoc!

**Comment by deivid-rodriguez** [comment]
Hi @bronzdoc!

So, it turns out that I now have an use case for labelling all PRs with a label. Have a look at the proposed workflow for managing the changelog at: https://github.com/rubygems/rubygems/pull/3792.
