### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/issue-triage#3]
We could:

* Tag PRs touching files not in `bundler/` with the `rubygems` tag.
* Tag PRs toching files in `.github/workflows` with the `CI` tag or something like that.

**Comment by duckinator** [comment]
@deivid-rodriguez I like both of these ideas.

**Comment by bronzdoc** [comment]
Somehow I missed this... sounds good @deivid-rodriguez

**Comment by bronzdoc** [comment]
Add this in https://github.com/rubygems/issue-triage/commit/6b456286e98afb0cb3d964da82ffb8ff084841d1

**Comment by deivid-rodriguez** [comment]
@bronzdoc Is this working? I was expecting for example, https://github.com/rubygems/rubygems/pull/3552, to have been labeled with the "Rubygems" label.

**Comment by bronzdoc** [comment]
@deivid-rodriguez It's fixed now. It was a combination of having the wrong label name for Rubygems also the `CI` label didn't exists. 

Also I was calling `add_label_to_an_issue` incorrectly but somehow Heroku is swallowing that exception so it always shows a success response in Github 🤷
